version: '3.0'

services:
  spotify-kafka:
    image: 'spotify/kafka'
    container_name: 'spotify-kafka'
    ports:
      - '2181:2181'
      - '9092:9092'
    environment:
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092

# docker-compose 